In [4]:
import numpy as np
A=np.array([[2, -2, 3], [1, 1, 1], [1, 3, -1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [5]:
#calculate eigenpairs :
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[ 3.  1. -2.]
[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [6]:
import numpy as np
A=np.array([[2, 0, 0], [0, 1, 0], [0, 0, -1]])
print(A)

[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [7]:
#calculate eigenpairs :
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[ 2.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
