In [1]:
import numpy as np
p = np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [6]:
q = np.array([[1,2],[4,5],[2,3]])
print(q)

[[1 2]
 [4 5]
 [2 3]]


In [7]:
c1 = np.add(p,q)
print(c1)

[[2 9]
 [6 6]
 [5 5]]


In [8]:
c2 = np.subtract(p,q)
print(c2)

[[ 0  5]
 [-2 -4]
 [ 1 -1]]


In [12]:
r = np.array([[1,3,1],[1,0,1]])
print(r)

[[1 3 1]
 [1 0 1]]


In [13]:
c3 = np.dot(p,r)
print(c3)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [21]:
determinant = np.linalg.det(c3)
print(determinant)

0.0


In [22]:
m = np.array([[1,1],[2,3]])
inverse = np.linalg.inv(m)
print(inverse)

[[ 3. -1.]
 [-2.  1.]]
