# **Singular Value Decomposition(SVD)**

 example using numpy(not using scikit-learn)

Given a rectangle matrix A, it can be factored into the form A=U∑V^T where U and V^T are ortho and ∑ is a diagonal matrix of singular values

In [ ]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

We will take a simple 3x4 matrix and look its SVD with numpy

In [ ]:
a = np.array([[1,2,3,4], [1,1,2,3], [0,1,1,0]])
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0]])

In [ ]:
u, s, vh = np.linalg.svd(a, full_matrices=True)
u.dot(u.T) #if this gives identity matrix it is an orthogonal matrix
s

array([6.7509, 1.1734, 0.2186])

In [ ]:
u.shape, s.shape, vh.shape

((3, 3), (3,), (4, 4))

In [ ]:
u

array([[ 0.8109,  0.0934, -0.5776],
       [ 0.57  , -0.3493,  0.7437],
       [ 0.1323,  0.9324,  0.3365]])

In [ ]:
vh

array([[ 0.2046,  0.3443,  0.5488,  0.7338],
       [-0.2181,  0.6561,  0.438 , -0.5746],
       [ 0.7598, -0.3431,  0.4167, -0.3625],
       [-0.5774, -0.5774,  0.5774,  0.    ]])

In [ ]:
s

[6.7509, 1.1734, 0]

In [ ]:
s = [6.7509, 1.1734, 0]

In [ ]:
np.dot(u,u.T)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
sd=np.diag(s) # makes a 3x3 diagonal matrix with x along the diagonal
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.    ]])

In [ ]:
sd.shape

(3, 3)

In [ ]:
b = np.zeros((3,4))

In [ ]:
b[:,:-1]=sd # assigning that first 3 columns of b comes from sd

In [ ]:
sigma=b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    ]])

In [ ]:
print(a)
print(np.dot(np.dot(u, sigma), vh)) # reconstructing a as product of u, s and vh

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]
[[ 1.0959  1.9567  3.0526  3.9542]
 [ 0.8764  1.0558  1.9322  3.0589]
 [-0.0559  1.0252  0.9693  0.0267]]


# Another Example

In [ ]:
a= np.array([[1,2,3,4], [1,1,2,3], [0,1,1,0], [0,2,2,0], [0,5,5,0]])
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0],
       [0, 2, 2, 0],
       [0, 5, 5, 0]])

In [ ]:
u, s, vh = np.linalg.svd(a)
u

array([[-0.5185, -0.5983,  0.6108, -0.    , -0.    ],
       [-0.3389, -0.512 , -0.7893,  0.    ,  0.    ],
       [-0.1433,  0.1125, -0.0114,  0.0312, -0.9827],
       [-0.2866,  0.225 , -0.0229, -0.9302,  0.0383],
       [-0.7166,  0.5626, -0.0572,  0.3658,  0.1812]])

In [ ]:
s

array([9.2296, 4.4454, 0.2312, 0.    ])

In [ ]:
vh

array([[-0.0929, -0.6149, -0.7079, -0.3349],
       [-0.2498,  0.375 ,  0.1252, -0.8839],
       [-0.7718,  0.3846, -0.3872,  0.3264],
       [ 0.5774,  0.5774, -0.5774,  0.    ]])

In [ ]:
u.shape, s.shape, vh.shape

((5, 5), (4,), (4, 4))