In [2]:
import numpy as np
v = np.array([1,-1, 2])
w = np.array([2,5,2])

In [3]:
print(v+w)

[3,4,4]

[3 4 4]


[3, 4, 4]

In [4]:
print(v-w)

[-1, -6, 0]

[-1 -6  0]


[-1, -6, 0]

In [6]:
#Scalar Multiplication
print(3*v)

[2, -2, 4]

[ 3 -3  6]


[2, -2, 4]

In [9]:
#length
print(np.linalg.norm(v))


2.449489742783178


In [10]:
#dot product
s = np.dot(v,w)
print(s)

1
